version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
  build:
    commands:
      - ls -l
      - docker build --tag "$IMAGE_URI" -f dockerdir/Dockerfile .
  post_build:
    commands:
      - cd dockerdir
      - docker push "$IMAGE_URI"
      - cd ..
      - printf '[{"name":"simple-app","imageUri":"%s"}]' "$IMAGE_URI" > images.json
artifacts:
  files: images.json
